server:
  port: 8088
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
#        - id: admin-service
#          uri: lb://ADMIN-SERVICE
#          predicates:
#            - Path=/gateway/sms-gate/**
#          filters:
#            - StripPrefix=1
#            - JwtAuthenticationFilter
        - id: ai-service
          uri: lb://AI-SERVICE
          predicates:
            - Path=/gateway/api/v1/chat/**
#            - Path=/gateway/api/v1/chat/topic/**
#            - Path=/gateway/api/v1/chat/user/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/gateway/api/v1/**
          filters:
            - StripPrefix=1

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

    discovery:
      enabled: true
  jwt:
    security: 843567893696976453275974432697R634976R738467TR678T34865R6834R8763T478378637664538745673865783678548735687R3
    expiration: 360000000
eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90


